version: '3.8'

services:

  nginx-1:
    build:
      context: ./
    restart: always
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/conf.d:/etc/nginx/conf.d
      - ./configs/pages:/usr/share/nginx/html
    ports:
      - "7080-7090:7080-7090"
      - "80:80"
    networks:
      - chatbot-net

networks:
  chatbot-net:
    name: chatbot-net
    driver: bridge