version: '3.3'

services:

  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    ports:
      - '9090:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - ./.env
    environment:
      DATABASE_URL: $DATABASE_URL
      NEXTAUTH_URL: $NEXTAUTH_URL
      NEXT_PUBLIC_VIEWER_URL: $NEXT_PUBLIC_VIEWER_URL
      ENCRYPTION_SECRET: $ENCRYPTION_SECRET
      ADMIN_EMAIL: $ADMIN_EMAIL
      SMTP_SECURE: $SMTP_SECURE
      SMTP_HOST: $SMTP_HOST
      SMTP_PORT: $SMTP_PORT
      SMTP_USERNAME: $SMTP_USERNAME
      SMTP_PASSWORD: $SMTP_PASSWORD
    networks:
      - chatbot-net

  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    ports:
      - '9091:3000'
    env_file:
      - ./.env
    environment:
      DATABASE_URL: $DATABASE_URL
      NEXT_PUBLIC_VIEWER_URL: $NEXT_PUBLIC_VIEWER_URL
      ENCRYPTION_SECRET: $ENCRYPTION_SECRET
    networks:
      - chatbot-net

networks:
  chatbot-net:
    name: chatbot-net
    driver: bridge