version: '3.3'

services:

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    env_file:
      - ./.env
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_ROOT_PASSWORD
      PUID: 1000
      PGID: 1000
    volumes:
      - mongodb_data:/data/db
      - mongodb_configdb:/data/configdb
    expose:
      - 27017
    networks:
      - chatbot-net

volumes:
  mongodb_data:
  mongodb_configdb:

networks:
  chatbot-net:
    name: chatbot-net
    driver: bridge