version: '3.3'

services:

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DRIVER: pgsql
      ADMINER_USERNAME: postgres
    ports:
      - 80:8080
    networks:
      - chatbot-net

networks:
  chatbot-net:
    name: chatbot-net
    driver: bridge