version: '3'

services:
  base: &base
    build:
      context: ./
    env_file: .env
    volumes:
      - chatwoot_data:/app/storage
    networks:
      - chatbot-net

  rails:
    <<: *base
    ports:
      - '3000:3000'
    restart: always
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    networks:
      - chatbot-net

  sidekiq:
    <<: *base
    restart: always
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    networks:
      - chatbot-net

volumes:
  chatwoot_data:

networks:
  chatbot-net:
    name: chatbot-net
    driver: bridge