version: '3'

services:

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    env_file:
      - ./.env
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'
    networks:
      - chatbot-net

volumes:
  redis_data:

networks:
  chatbot-net:
    name: chatbot-net
    driver: bridge